setInterval(()=>{
const astroide = require("./main")
console.log(astroide.number(10))
console.log(astroide.oyun("seviyor_sevmiyor"))
console.log(astroide.oyun("yazı_tura"))
console.log(astroide.oyun("zar"))
console.log(astroide.oyun("slots"))
console.log(astroide.sayi(3))
console.log(astroide.sayi(4, 20))
console.log(astroide.sayi(5, 10, 20))
console.log(astroide.renk())
console.log(astroide.renk("2"))
},)