name: Publish

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
