name: Publish a release

on: workflow_dispatch

env:
  NODE_VERSION: 12

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Download package
        uses: actions/download-artifact@v2
        with:
            name: release_id
      - run: echo "release_id=$(cat release.txt)" >> $GITHUB_ENV
      - name: Publish release
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false
            })
  publish-npm:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download package
        uses: actions/download-artifact@v2
        with:
            name: package
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      - run: npm publish $(ls *.tgz) --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: package
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          scope: "@aaronpowell"
      - run: echo "registry=https://npm.pkg.github.com/@aaronpowell" >> .npmrc
      - run: npm publish $(ls *.tgz) --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
