name: Publish

on:
  release:
    types: [created]

jobs:

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm config set registry=https://npm.pkg.github.com/@astroidejs
      - run: npm publish --scope=@astroidejs
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
