name: Testing in Node 12
on: [push,pull_request]
jobs:
  test:
    name: Node.JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version: 12
      - run: npm i
      - run: npm run test
