name: Testing
on: workflow_dispatch
jobs:
  test:
    name: Node.JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and Installing Node
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 6

      - name: Install dependencies
        run: npm i

      - name: Run Test
        run: npm run test
